### ISSUE TITLE
Render jsonify templates within controller context

### ISSUE THREAD

**Issue by wireframe** [bsiggelkow/jsonify-rails#4]
similar to haml, my templates have access to certain controller/helper methods instead of solely accessing instance variables.

a great example of this is when integrating with Devise authentication and accessing the `current_user` method from within my templates.

how difficult is it to expose these same methods within jsonify templates?

**Comment by bsiggelkow** [comment]
Have you tried calling your helper methods from within the jsonify template? As far as I know it should work fine. I tried a simple test that used ActionView::Helpers::TextHelper.pluralize:

json.hello 'world'
json.goodbye 'universe'
json.test pluralize(2,'person')

and it rendered correctly:

{
  "hello": "world",
  "goodbye": "universe",
  "test": "2 people"
}

Let me know if there's a specific use case that is not working for you.

**Comment by bsiggelkow** [comment]
From what I can tell, there is not an issue here.
